# Generated by Django 5.1.7 on 2025-03-19 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('about', models.CharField(default='name', max_length=100)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Recital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('about', models.CharField(default='name', max_length=100)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('about', models.CharField(default='name', max_length=100)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('absent', models.BooleanField(default=False)),
                ('late', models.BooleanField(default=False)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.classes')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'classes', 'date')},
            },
        ),
    ]
